config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pages#index'
  get  '/timeline', to: 'posts#timeline'
  devise_for  :users, controllers: { registrations: 'users/registrations' }
  resources   :users, only: [:index, :show] do
    member do
      get :bookmark, :following, :followers
    end
  end
  resources :shops do
    resources   :posts, only: [:index, :new, :create]
    resources   :bookmarks, only: [:create, :destroy]
  end
  resources   :posts, except: [:index, :new, :create] do
    resources :comments, only: [:create, :destroy]
  end
  resources   :likes, only: [:create, :destroy]
  resources   :relationships, only: [:create, :destroy]
end

app/models/shop.rb
class Shop < ApplicationRecord
  mount_uploader :picture, PictureUploader

  has_many :posts, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_users, through: :bookmarks, source: :user

  validates :name, presence: true
  validates :station, presence: true, length: { maximum: 30 }

  scope :newest, -> { order(created_at: :desc) }

  def bookmarks_count
    bookmarked_users.count
  end

  def self.ransackable_attributes(auth_object = nil)
    %w(name address station)
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :admin_user, only: [:destroy]
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  def index
    @q = Shop.ransack(params[:q])
    if params[:sort] == "popular"
      @shops = Shop.
        joins(:bookmarks).
        group("shops.id").
        order(Arel.sql("count(bookmarks.id) desc")).
        page(params[:page])
    else
      @shops = @q.result(distinct: true).newest.page(params[:page])
    end
  end

  def show
    @posts = @shop.posts.includes(:user).order(updated_at: :desc).limit(4)
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)

    if @shop.save
      redirect_to @shop, notice: "お店「#{@shop.name}」を登録しました。"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @shop.update(shop_params)
      redirect_to @shop, notice: "お店「#{@shop.name}」を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @shop.destroy
    redirect_to shops_path, notice: "お店「#{@shop.name}」を削除しました。"
  end

  private

  def admin_user
    unless current_user.admin?
      flash[:alert] = "お店を削除することはできません。"
      redirect_back(fallback_location: root_path)
    end
  end

  def shop_params
    params.require(:shop).permit(:name,
                                 :menu,
                                 :hour,
                                 :holiday,
                                 :address,
                                 :phone,
                                 :url,
                                 :picture,
                                 :remove_picture,
                                 :picture_cache,
                                 :station)
  end

  def set_shop
    @shop = Shop.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
  def display_image(shop)
    if shop.picture?
      image_tag(shop.picture.url, class: 'card-img-top rounded', alt: "#{shop.name}")
    else
      image_tag("/assets/noimage.jpg", class: 'card-img-top rounded', alt: "#{shop.name}")
    end
  end
end

app/views/shops/_form.html.erb
<% if shop.errors.present? %>
  <ul id="error_explanation">
    <% shop.errors.full_messages.each do |message| %>
      <li class="text-danger"><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: shop, local: true do |f| %>
  <div class="form-group">
    <p><%= f.label :name %><span class="need">*</span></p>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :menu %>
    <%= f.text_area :menu, rows: 5, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :hour %>
    <%= f.text_field :hour, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :holiday %>
    <%= f.text_field :holiday, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :station %><span class="need">*</span>
    <%= f.text_field :station, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :picture %><br>
    <% if shop.picture? %>
      <%= image_tag(shop.picture.url, class: 'img-thumbnail resize d-block mt-2 mb-3') %>
      <%= f.label :remove_picture, for: 'exampleCheck1', class: 'mb-4' do %>
        <%= f.check_box :remove_picture, id: 'exampleCheck1' %>
        <small>画像を削除する</small>
      <% end %>
    <% end %>
    <%= f.file_field :picture, class: 'form-control-file', accept: 'image/jpeg,image/png'  %>
    <%= f.hidden_field :picture_cache %>
  </div>
  <%= f.submit nil, class: 'btn btn-primary mt-4' %>
<% end %>

app/views/shops/edit.html.erb
<% provide(:title, "お店編集") %>
<% breadcrumb :shop_edit, @shop %>

<div class="row  justify-content-center px-3 py-5">
  <div class="col-md-8 p-5 border rounded shadow-sm">
    <h2 class="mb-4">お店編集</h2>
    <%= render 'form', shop: @shop %>
  </div>
</div>

app/views/shops/index.html.erb
<% provide(:title, "お店を探す") %>
<% breadcrumb :shops %>

<h2 class="pt-5 pb-3">お店を探す</h2>
<%= search_form_for @q, class: 'mb-5' do |f| %>
  <div class="form-group row">
    <div class="col-md-5 my-2">
      <%= f.search_field :name_cont, class: 'form-control', placeholder: "お店の名前で検索" %>
    </div>
    <div class="col-md-5 my-2">
      <%= f.search_field :address_or_station_cont, class: 'form-control', placeholder: "住所・駅名で検索" %>
    </div>
    <div class="col-2 my-2">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>
<div class="mb-5">
  <%= link_to '新着順', shops_path, class: "btn btn-outline-success mr-3 #{"active" unless params[:sort]}" %>
  <%= link_to '人気順', { controller: "shops", action: "index", sort: "popular" }, class: "btn btn-outline-success mr-3 #{"active" if params[:sort]}" %>
</div>
<%= link_to 'お店を登録する', new_shop_path, class: 'btn btn-outline-primary mb-5' %>

<div class="mb-5">
  <%= paginate @shops %>
  <%= page_entries_info @shops %>
</div>

<div class="row">
  <%= render partial: "shared/shop", collection: @shops, locals: { col: "col-sm-6 col-md-4 col-xl-3" } %>
</div>

<div class="mb-5">
  <%= paginate @shops %>
</div>

app/views/shops/new.html.erb
<% provide(:title, "お店登録") %>
<% breadcrumb :shop_new %>

<div class="row  justify-content-center px-3 py-5">
  <div class="col-md-8 p-5 border rounded shadow-sm">
    <h2 class="mb-4">お店登録</h2>
    <%= render 'form', shop: @shop %>
  </div>
</div>

app/views/shops/show.html.erb
<% provide(:title, "#{@shop.name}") %>
<% breadcrumb :shop, @shop %>
  <div class="row justify-content-center">
    <div class="col-md-8 mt-4">
      <%= display_image(@shop) %>
      <div class="row my-4">
        <h2 class="col-9"><%= @shop.name %></h2>
        <div id="bookmark-btn" class="bookmark text-right col-3">
          <%= render 'bookmarks/bookmark', shop: @shop %>
        </div>
      </div>

      <div class="post-wrapper">
        <div class="d-flex justify-content-between mt-5 my-3">
          <h3>レビュー</h3>
          <% if @posts.present? && @shop.posts_count > 4 %>
            <p class="d-flex align-items-center small">
              <%= link_to 'もっと見る', shop_posts_path(@shop), class: "text-muted" %>
            </p>
          <% end %>
        </div>

        <% if @posts.present? %>
          <%= render partial: "shared/post", collection: @posts %>
        <% else %>
          <p>レビューはまだ投稿されていません。</p>
        <% end %>
        <%= link_to 'レビューを投稿する', new_shop_post_path(@shop), class: 'btn btn-outline-primary mt-5' %>
      </div>

      <div class="info-wrapper">
        <h3 class="mt-5 my-3">基本情報</h3>
        <table class="table table-bordered">
          <tbody>
            <tr>
              <th class="bg-light"><%= Shop.human_attribute_name(:name) %></th>
              <td><%= @shop.name %></td>
            </tr>
            <tr>
              <th class="bg-light"><%= Shop.human_attribute_name(:menu) %></th>
              <td><%= auto_link(simple_format(h(@shop.menu.presence || '-'), {}, sanitize: false), html: { target: '_blank' }) %></td>
            </tr>
            <tr>
              <th class="bg-light"><%= Shop.human_attribute_name(:hour) %></th>
              <td><%= @shop.hour.presence || '-' %></td>
            </tr>
            <tr>
              <th class="bg-light"><%= Shop.human_attribute_name(:holiday) %></th>
              <td><%= @shop.holiday.presence || '-' %></td>
            </tr>
            <tr>
              <th class="bg-light"><%= Shop.human_attribute_name(:station) %></th>
              <td><%= @shop.station %></td>
            </tr>
            <tr>
              <th class="bg-light"><%= Shop.human_attribute_name(:address) %></th>
              <td><%= @shop.address.presence || '-' %></td>
            </tr>
            <tr>
              <th class="bg-light"><%= Shop.human_attribute_name(:phone) %></th>
              <td><%= @shop.phone.presence || '-' %></td>
            </tr>
            <tr>
              <th class="bg-light"><%= Shop.human_attribute_name(:url) %></th>
              <td><a href="<%= @shop.url.presence || '#' %>", target="_blank"><%= @shop.url.presence || '-' %></a></td>
            </tr>
            <tr>
              <th class="bg-light"><%= Shop.human_attribute_name(:updated_at) %></th>
              <td><%= simple_time(@shop.updated_at) %></td>
            </tr>
          </tbody>
        </table>
        <%= link_to 'お店の情報を編集する', edit_shop_path(@shop), class: 'btn btn-outline-primary mt-5' %>
        <% if user_signed_in? && current_user.admin? %>
          <div class="pt-5">
            <%= link_to '削除', shop_path(@shop), method: :delete, data: { confirm: "「#{@shop.name}」を削除します。よろしいですか？"}, class: 'text-light btn btn-danger' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>