config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pages#index'
  get  '/timeline', to: 'posts#timeline'
  devise_for  :users, controllers: { registrations: 'users/registrations' }
  resources   :users, only: [:index, :show] do
    member do
      get :bookmark, :following, :followers
    end
  end
  resources :shops do
    resources   :posts, only: [:index, :new, :create]
    resources   :bookmarks, only: [:create, :destroy]
  end
  resources   :posts, except: [:index, :new, :create] do
    resources :comments, only: [:create, :destroy]
  end
  resources   :likes, only: [:create, :destroy]
  resources   :relationships, only: [:create, :destroy]
end

app/views/shared/_post.html.erb
<%= link_to post_path(post), id: "post-#{post.id}" do %>
  <div class="post-card-t border shadow-sm rounded mt-5 pt-3 px-3 pb-1">
    <div class="row mb-1">
      <div class="col-md-1 text-center">
        <%= display_user_image(post.user, 'resize-50') %>
      </div>
      <div class="col-md-11 md-post">
        <p class="mb-2 md-text-center"><b><%= post.user.username %></b></p>
        <p class="mb-2"><%= "お店：#{post.shop.name}" %></p>
        <div class="py-2 border-top border-bottom">
          <h3 class="mb-3"><%= post.title %></h3>
          <p><%= shorten_description(post) %></p>
        </div>
        <% if post.recomend.present? %>
          <p class="py-2"><%= "おすすめメニュー：#{post.recomend}" %></p>
        <% end %>
        <div class="text-center my-3">
          <%= display_post_image(post, "resize-200") %>
        </div>

        <div class="row mt-2">
          <div class="col-5 text-left">
            <p class="like-t d-inline-block">
              <% if already_like?(post) %>
                <i class="fas fa-heart mr-1"></i>
              <% else %>
                <i class="far fa-heart mr-1"></i>
              <% end %>
              <%= post.likes_count %>
            </p>
            <p class="comment-t d-inline-block">
              <i class="far fa-comments ml-2 mr-1"></i>
              <%= post.comments_count %>
            </p>
          </div>
          <p class="col-7 small text-muted text-right"><%= post_time(post.updated_at) %></p>
        </div>
      </div>
    </div>
  </div>
<% end %>
<% if current_user?(post.user) %>
  <div class="py-3">
    <%= link_to '編集', edit_post_path(post), class: 'text-light btn btn-primary mr-4' %>
    <%= link_to '削除', post_path(post), method: :delete, data: { confirm: "「#{post.title}」を削除します。よろしいですか？"}, class: 'text-light btn btn-danger' %>
  </div>
<% end %>

app/views/shared/_shop.html.erb
<div class="<%= "#{col} mb-5" %>">
  <%= link_to shop_path(shop), id: "shop-#{shop.id}" do %>
    <div class="card shadow-sm h-100">
      <%= display_image(shop) %>
      <div class="card-body pb-2">
        <h5 class="card-title"><%= shop.name %></h5>
        <p class="card-text mb-1"><i class="fas fa-subway mr-2"></i><%= shop.station %></p>
        <p class="card-text"><i class="fas fa-map-marker-alt mr-2"></i><%= shop.address.presence || '-' %></p>
      </div>
      <div class="card-footer bg-white">
        <p class="bookmark-t card-text d-inline-block">
          <% if shop.bookmarks_count == 0 %>
            <i class="far fa-star mr-1"></i>0
          <% else %>
            <i class="fas fa-star mr-1"></i><%= shop.bookmarks_count %>
          <% end %>
        </p>
        <p class="post-t card-text d-inline-block ml-3">
          <i class="far fa-comment-dots mr-1"></i><%= shop.posts_count %>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_user.html.erb
<div class="<%="#{col} mb-5"%>">
  <%= link_to user_path(user), id: "user-#{user.id}" do %>
    <div class="card shadow-sm h-100">
      <div class="card-body">
        <div class="text-center">
          <%= display_user_image(user, 'resize') %>
          <h5 class="card-title mt-2"><%= user.username %></h5>
        </div>
        <div class="introduction mb-2">
          <p class="card-text"><%= shorten_introduction(user) %></p>
        </div>
        <p class="card-text small"><%= "レビュー：#{user.posts_count}" %></p>
        <p class="card-text small"><%= "いいね：#{user.get_likes}" %></p>
        <p class="card-text small"><%= "お気に入りのお店：#{user.favorite_shop_name}" %></p>
      </div>
    </div>
  <% end %>
</div>