config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pages#index'
  get  '/timeline', to: 'posts#timeline'
  devise_for  :users, controllers: { registrations: 'users/registrations' }
  resources   :users, only: [:index, :show] do
    member do
      get :bookmark, :following, :followers
    end
  end
  resources :shops do
    resources   :posts, only: [:index, :new, :create]
    resources   :bookmarks, only: [:create, :destroy]
  end
  resources   :posts, except: [:index, :new, :create] do
    resources :comments, only: [:create, :destroy]
  end
  resources   :likes, only: [:create, :destroy]
  resources   :relationships, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :picture, PictureUploader

  belongs_to :user
  counter_culture :user
  belongs_to :shop
  counter_culture :shop

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  validates :title, presence: true, length: { maximum: 30 }
  validates :description, presence: true
  validates :recomend, length: { maximum: 30 }

  scope :timeline, -> current_user {
    where(user_id: current_user.following.ids).
      order(updated_at: :desc)
  }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :timeline]
  before_action :set_post, only: [:edit, :update, :destroy]
  before_action :set_shop, only: [:index, :new, :create]

  def index
    @posts = @shop.posts.includes(:user).page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:user).all
    @comment = Comment.new
    @shop = @post.shop
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.shop_id = @shop.id
    if @post.save
      redirect_to post_path(@post), notice: "レビュー「#{@post.title}」を投稿しました。"
    else
      render :new
    end
  end

  def edit
    @shop = @post.shop
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "レビュー「#{@post.title}」を更新しました。"
    else
      @shop = @post.shop
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, notice: "レビュー「#{@post.title}」を削除しました。"
  end

  def timeline
    @q = User.ransack(params[:q])
    @posts = Post.includes(:user, :shop).timeline(current_user).page(params[:page])
  end

  private

  def post_params
    params.require(:post).permit(:title,
                                 :description,
                                 :recomend,
                                 :picture,
                                 :remove_picture,
                                 :picture_cache,
                                 :shop_id)
  end

  def set_post
    @post = current_user.posts.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def set_shop
    @shop = Shop.find(params[:shop_id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def display_post_image(post, resize)
    if post.picture?
      image_tag(post.picture.url, class: "#{resize}", alt: "#{post.title}の写真")
    end
  end

  def shorten_description(post)
    if post.description.length >= 100
      "#{post.description[0...100]}…"
    else
      post.description
    end
  end

  def post_time(time)
    "#{time_ago_in_words(time)}　#{simple_time(time)}"
  end

  def delete_comment(post, comment)
    if comment.user == current_user
      link_to(
        "削除する",
        post_comment_path(post, comment),
        method: :delete,
        data: { confirm: "コメントを削除します。よろしいですか？" },
        class: 'text-danger'
      )
    end
  end
end

app/views/posts/_comment.html.erb
<div class="border-top border-bottom p-2 mb-1">
  <div class="row">
    <div class="col-1 text-center">
      <%= link_to user_path(comment.user) do %>
        <%= display_user_image(comment.user, 'resize-30') %>
      <% end %>
    </div>
    <div class="col-10 ml-1 mb-2">
      <p class="mb-1"><b><%= link_to comment.user.username, user_path(comment.user) %></b></p>
      <p><%= auto_link(simple_format(h(comment.content), {}, sanitize: false, class: 'py-2'), html: { target: '_blank' }) %></p>
    </div>
  </div>
  <p class="small text-muted text-right">
    <%= "#{post_time(comment.created_at)}" %>
    <%= delete_comment(post, comment) %>
  </p>
</div>

app/views/posts/edit.html.erb
<% provide(:title, "#{@shop.name}のレビュー編集") %>
<% breadcrumb :post_edit, @shop , @post%>

<div class="row  justify-content-center px-3 py-5">
  <div class="col-md-8 p-5 border rounded shadow-sm">
    <h2 class="mb-4"><%= "#{@shop.name}のレビュー編集" %></h2>
    <div class="nav justify-content-end">
      <%= link_to '戻る', post_path(@post), class: 'text-muted' %>
    </div>

    <% if @post.errors.present? %>
      <ul id="error_explanation">
        <% @post.errors.full_messages.each do |message| %>
          <li class="text-danger"><%= message %></li>
        <% end %>
      </ul>
    <% end %>

    <%= form_with(model: @post, local: true ) do |f| %>
      <div class="form-group">
        <%= f.label :title %><span class="need">*</span>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :description %><span class="need">*</span>
        <%= f.text_area :description, rows: 5, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :recomend %>
        <%= f.text_field :recomend, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :picture %><br>
        <% if @post.picture? %>
          <%= image_tag(@post.picture.url, class: 'img-thumbnail resize d-block mt-2 mb-3') %>
          <%= f.label :remove_picture, for: 'exampleCheck1', class: 'mb-4' do %>
            <%= f.check_box :remove_picture, id: 'exampleCheck1' %>
            <small>画像を削除する</small>
          <% end %>
        <% end %>
        <%= f.file_field :picture, class: 'form-control-file', accept: 'image/jpeg,image/png'  %>
        <%= f.hidden_field :picture_cache %>
      </div>
      <%= f.submit nil, class: 'btn btn-primary mt-4' %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<% provide(:title, "#{@shop.name}のレビュー一覧") %>
<% breadcrumb :posts, @shop %>

<div class="row justify-content-center">
  <div class="col-md-8">
    <h2 class="pt-5 pb-3"><%= link_to @shop.name, shop_path(@shop) %>のレビュー一覧</h2>
    <div class="row justify-content-end pb-3">
      <%= link_to 'お店に戻る', shop_path(@shop) %>
    </div>
    <div class="mb-5">
      <%= paginate @posts %>
      <%= page_entries_info @posts %>
    </div>

    <%= render partial: "shared/post", collection: @posts %>

    <div class="mb-5">
      <%= paginate @posts %>
    </div>
    <%= link_to 'レビューを投稿する', new_shop_post_path(@shop), class: 'btn btn-outline-primary mt-3' %>
  </div>
</div>

app/views/posts/new.html.erb
<% provide(:title, "#{@shop.name}のレビュー投稿") %>
<% breadcrumb :post_new, @shop %>

<div class="row  justify-content-center px-3 py-5">
  <div class="col-md-8 p-5 border rounded shadow-sm">
    <h2 class="mb-4"><%= "#{@shop.name}のレビュー投稿" %></h2>
    <% if @post.errors.present? %>
      <ul id="error_explanation">
        <% @post.errors.full_messages.each do |message| %>
          <li class="text-danger"><%= message %></li>
        <% end %>
      </ul>
    <% end %>

    <%= form_with(model: [ @shop, @post ], local: true ) do |f| %>
      <div class="form-group">
        <%= f.label :title %><span class="need">*</span>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :description %><span class="need">*</span>
        <%= f.text_area :description, rows: 5, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :recomend %>
        <%= f.text_field :recomend, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :picture %><br>
        <% if @post.picture? %>
          <%= image_tag(@post.picture.url, class: 'img-thumbnail resize d-block mt-2 mb-3') %>
          <%= f.label :remove_picture, for: 'exampleCheck1', class: 'mb-4' do %>
            <%= f.check_box :remove_picture, id: 'exampleCheck1' %>
            <small>画像を削除する</small>
          <% end %>
        <% end %>
        <%= f.file_field :picture, class: 'form-control-file', accept: 'image/jpeg,image/png'  %>
        <%= f.hidden_field :picture_cache %>
      </div>
      <%= f.submit "投稿する", class: 'btn btn-primary mt-4' %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<% provide(:title, "#{@shop.name}のレビュー詳細") %>
<% breadcrumb :post, @shop, @post %>

<div class="row justify-content-center">
  <div class="col-lg-8">
    <h2 class="pt-5 pb-3"><%= link_to @shop.name, shop_path(@shop) %>のレビュー詳細</h2>

    <div class="border shadow-sm rounded mt-3 pt-3 px-3 pb-1">
      <div class="row mb-1">
        <div class="col-md-1 text-center">
          <%= link_to user_path(@post.user) do %>
            <%= display_user_image(@post.user, 'resize-50') %>
          <% end %>
        </div>
        <div class="col-md-11 md-post">
          <p class="mb-2 md-text-center"><b><%= link_to @post.user.username, user_path(@post.user) %></b></p>
          <p class="mb-2">お店：<%= link_to @shop.name, shop_path(@shop) %></p>
          <div class="py-2 border-top border-bottom">
            <h3 class="mb-3"><%= @post.title %></h3>
            <p><%= auto_link(simple_format(h(@post.description), {}, sanitize: false), html: { target: '_blank' }) %></p>
          </div>

          <% if @post.recomend.present? %>
            <p class="py-2"><%= "おすすめメニュー：#{@post.recomend}" %></p>
          <% end %>
          <div class="text-center my-3">
            <%= display_post_image(@post, "resize-max") %>
          </div>

          <div class="row mt-2">
            <div class="col-5 text-left">
              <div id="like-btn" class="d-inline-block like-t">
                <%= render 'likes/like', post: @post %>
              </div>
              <div class="d-inline-block comment-t">
                <i class="far fa-comments ml-2 mr-1"></i>
                <%= @post.comments_count %>
              </div>
            </div>
            <p class="col-7 small text-muted text-right"><%= post_time(@post.updated_at) %></p>
          </div>
        </div>
      </div>
    </div>

    <% if user_signed_in? && current_user?(@post.user) %>
      <div class="my-3">
        <%= link_to '編集', edit_post_path(@post), class: 'text-light btn btn-primary mr-4' %>
        <%= link_to '削除', post_path(@post), method: :delete, data: { confirm: "「#{@post.title}」を削除します。よろしいですか？"}, class: 'text-light btn btn-danger' %>
      </div>
    <% end %>

    <div class="comment-wrapper">
      <div>
        <h5 class="mt-5"><%= "コメント #{@post.comments_count}件" %></h5>
        <%= render partial: "posts/comment", collection: @comments, locals: { post: @post } %>
      </div>
      <div>
        <% if user_signed_in? %>
          <h5 class="mt-4">コメント投稿</h5>
          <% if @comment.errors.present? %>
            <ul id="error_explanation">
              <% @comment.errors.full_messages.each do |message| %>
                <li class="text-danger"><%= message %></li>
              <% end %>
            </ul>
          <% end %>
          <%= form_with(model: [@post, @comment], local: true) do |f| %>
            <div class="form-group">
              <%= f.text_area :content, rows: 3, class: 'form-control' %>
            </div>
            <%= f.submit '送信', class: 'btn btn-primary' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/timeline.html.erb
<% provide(:title, "タイムライン") %>
<% breadcrumb :timeline %>

<div class="row justify-content-center">
  <div class="col-md-8">
    <h2 class="pt-5 pb-3">タイムライン</h2>

    <div class="my-5">
      <%= paginate @posts %>
      <%= page_entries_info @posts %>
    </div>

    <% if @posts.empty? %>
      <p>ユーザーをフォローしましょう</p>
      <%= search_form_for @q, url: users_path, method: :get, class: 'mt-3' do |f| %>
      <div class="form-group row">
        <div class="col-9">
          <%= f.search_field :username_or_introduction_cont, class: 'form-control', placeholder: "名前・自己紹介の内容で検索" %>
        </div>
        <div class="col-2">
          <%= f.submit class: 'btn btn-primary' %>
        </div>
      </div>
      <% end %>
    <% end %>

    <%= render partial: "shared/post", collection: @posts %>

    <div class="my-5">
      <%= paginate @posts %>
    </div>
  </div>
</div>