config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pages#index'
  get  '/timeline', to: 'posts#timeline'
  devise_for  :users, controllers: { registrations: 'users/registrations' }
  resources   :users, only: [:index, :show] do
    member do
      get :bookmark, :following, :followers
    end
  end
  resources :shops do
    resources   :posts, only: [:index, :new, :create]
    resources   :bookmarks, only: [:create, :destroy]
  end
  resources   :posts, except: [:index, :new, :create] do
    resources :comments, only: [:create, :destroy]
  end
  resources   :likes, only: [:create, :destroy]
  resources   :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<div class="bg-light border-top border-bottom d-sp scroll_bar">
  <%= breadcrumbs separator: " &rsaquo; ", class: 'container py-2' %>
</div>
<footer class="py-5 bg-dark d-flex justify-content-end">
  <p class="text-light pr-3 m-0">&copy; 2019 Shogo</p>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-yellow fixed-top">
  <%= link_to root_path, class: 'navbar-brand' do %>
    <h1 class="mb-0 d-inline-block">Burger Mania!</h1>
    <%= image_tag('/assets/burger-icon.png', class: 'header-icon d-inline-block align-top') %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item mr-3">
        <%= link_to 'お店を探す', shops_path, class: 'nav-link' %>
      </li>
      <li class="nav-item mr-3">
        <%= link_to 'ユーザーを探す', users_path, class: 'nav-link' %>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item mr-3">
          <%= link_to 'タイムライン', timeline_path, class: 'nav-link' %>
        </li>
        <li class="nav-item mr-3">
          <%= link_to user_path(current_user), class: 'nav-link' do %>
            <%= display_user_image(current_user, 'resize-30') %>
            <%= current_user.username %>さん
          <% end %>
        </li>

        <% if current_user.admin? %>
          <li class="nav-item mr-3">
            <%= link_to '管理画面', rails_admin_path, class: 'nav-link' %>
          </li>
        <% end %>

        <li class="nav-item">
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>

        <li class="nav-item mr-3">
          <%= link_to '新規登録', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'ログイン', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>

    </ul>
  </div>
</nav>

<% if flash.notice.present? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if flash.alert.present? %>
  <div class="alert alert-danger" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container my-5">
      <%= breadcrumbs separator: " &rsaquo; ", class: 'breadcrumbs small d-pc py-2' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <% if controller.controller_name == 'pages' && controller.action_name == 'index' %>
      <div class="top">
        <div class="top-container text-center">
          <h2 class="pb-3">次に食べたい<span class="d-inline-block">ハンバーガー</span>が見つかる</h2>
          <%= search_form_for @q, url: shops_path, method: :get, class: 'mb-5' do |f| %>
            <div class="form-group row justify-content-center">
              <div class="col-sm-4 col-10 m-2">
                <%= f.search_field :name_cont, class: 'form-control', placeholder: "お店の名前で検索" %>
              </div>
              <div class="col-sm-4 col-10 m-2">
                <%= f.search_field :address_or_station_cont, class: 'form-control', placeholder: "住所・駅名で検索" %>
              </div>
              <div class="m-2">
                <%= f.submit class: 'btn btn-primary' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>

    <div class="container my-5">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>